spring:
  data:
    mongodb:
      first:
        uri: mongodb://用户名:密码@ip:port/mongo_demo?authSource=admin
      second:
        uri: mongodb://ip:port/mongo_demo
      third:
        uri: mongodb://ip:port/mongo_demo
